name: Rust

on:
  push:
    branches: ["master"]
    paths:
      - crates/**
      - rust.yml
      - Cargo.lock
      - Cargo.toml
  pull_request:
    branches: ["master"]
    paths:
      - crates/**
      - rust.yml
      - Cargo.lock
      - Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      - run: rustup component add rustfmt
      - run: cargo fmt --check
